// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaMav6dPlX7MOJnqI8oczlp5SCe_WSI6U',
    appId: '1:943946517872:android:5a6aa03d9417a6b28513b5',
    messagingSenderId: '943946517872',
    projectId: 'customizable-app',
    storageBucket: 'customizable-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC6vqP9cvETEmh93gQWM9Ua2nFK_5Xrbo',
    appId: '1:943946517872:ios:a48ba338db9eeb0f8513b5',
    messagingSenderId: '943946517872',
    projectId: 'customizable-app',
    storageBucket: 'customizable-app.appspot.com',
    iosClientId: '943946517872-iogg9aog9ecbrccccv3dagaogddkeisk.apps.googleusercontent.com',
    iosBundleId: 'com.example.customizableApp',
  );
}
